spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

---
spring:
  profiles: default
ribbon:
  eureka:
   enabled: false
weatherbus-weather:
  ribbon:
    listOfServers: weatherbus-weather-dev.cfapps.io:80
weatherbus-bus:
  ribbon:
    listOfServers: weatherbus-bus-dev.cfapps.io:80
weatherbus-crime:
  ribbon:
    listOfServers: weatherbus-crime-dev.cfapps.io:80

---
spring:
  profiles: goldengardens
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/wbpgg
ribbon:
  eureka:
   enabled: false
weatherbus-weather:
  ribbon:
    listOfServers: localhost:8001
weatherbus-bus:
  ribbon:
    listOfServers: localhost:8002

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
