---    
platform: linux
image: "docker:///java#8"
inputs:
  - name: weatherbus-source
outputs:
  - name: build
    path: artifacts
run:
  path: "weatherbus-source/gradlew"
  args: ["copyJar", "-pweatherbus-source"]
params:
  "TERM": "xterm"

