---    
platform: linux
image: "docker:///java#8"
inputs:
  - name: prime
outputs:
  - name: build
    path: prime/artifacts
run:
  path: "prime/gradlew"
  args: ["copyJar", "-pprime"]
params:
  "TERM": "xterm"

