---    
platform: linux
image: "docker:///java#8"
inputs:
- name: weatherbus-source
run:
  path: "weatherbus-source/gradlew"
  args: ["build", "-pweatherbus-source"]
params:
  "TERM": "xterm"
outputs:
- name: jar
  path: "weatherbus-source/build/libs/weatherbus-0.0.1-SNAPSHOT.jar"

