resources:
- name: prime
  type: git
  source:
    uri: https://github.com/gbcm/weatherbus.git
    branch: master

- name: prime-version
  type: semver
  source:
    bucket: weatherbus-pipeline-artifacts
    key: prime-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
    initial_version: 0.0.1
- name: prime-rc
  type: s3
  source:
    bucket: weatherbus-pipeline-artifacts
    regexp: weatherbus-(\d+\.\d+\.\d+)-rc\.\d+\.jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
- name: prime-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: seattle-beach
    space: development

- name: weather-version
  type: semver
  source:
    bucket: weatherbus-pipeline-artifacts
    key: weather-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
    initial_version: 0.0.1
- name: weather-rc
  type: s3
  source:
    bucket: weatherbus-pipeline-artifacts
    regexp: weatherbus-weather-.*\.jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
- name: weather-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: seattle-beach
    space: development

- name: weather
  type: git
  source:
    uri: https://github.com/gbcm/weatherbus-weather.git
    branch: master

jobs:
- name: prime
  serial_groups: [version]
  plan:
    - get: prime
      trigger: true
    - get: prime-version
      params: {pre: rc}
    - task: build
      file: prime/concourse/build.yml
    - put: prime-rc
      params: {from: build/weatherbus-.*\.jar}
    - put: prime-version
      params: {file: prime-version/number}
- name: prime-deploy
  serial: true
  plan:
    - get: prime-rc
      trigger: true
      passed: [prime]
    - get: prime
      passed: [prime]
    - put: prime-cf
      params:
        manifest: prime/manifest.yml
        path: prime-rc/weatherbus-*.jar

- name: weather
  plan:
    - get: weather
      trigger: true
    - task: build
      file: weather/concourse/build.yml
    - put: weather-rc
      params: {from: "weather/build/libs/weatherbus-weather-0.0.1-SNAPSHOT.jar"} #  (╯°□°)╯︵ ┻━┻

- name: weather-deploy
  serial: true
  plan:
    - get: weather-rc
      trigger: true
      passed: [weather]
    - get: weather
      passed: [weather]
    - put: weather-cf
      params:
        manifest: weather/manifest.yml
        path: weather-rc/weatherbus-weather-*.jar
