resources:
- name: prime
  type: git
  source:
    uri: https://github.com/gbcm/weatherbus.git
    branch: master
- name: prime-version
  type: semver
  source:
    bucket: weatherbus-pipeline-artifacts
    key: prime-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
    initial_version: 0.0.1
- name: prime-rc
  type: s3
  source:
    bucket: weatherbus-pipeline-artifacts
    regexp: weatherbus-(\d\.\d\.\d)-SNAPSHOT.jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
- name: prime-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: seattle-beach
    space: development
- name: web
  type: git
  source:
    uri: https://github.com/sgravrock/weatherbus-web.git
    branch: master

jobs:
- name: prime
  serial_groups: [version]
  plan:
    - get: prime
      trigger: true
    - get: prime-version
      params: {pre: rc}
    - task: build
      file: prime/concourse/build.yml
    - put: prime-rc
      params: {from: build/weatherbus-.*.jar}
    - put: prime-version
      params: {file: prime-version/number}
- name: prime-deploy
  serial: true
  plan:
    - get: prime-rc
      trigger: true
      passed: [prime]
    - get: prime
      passed: [prime]
    - put: prime-cf
      params:
        manifest: prime/manifest.yml
        path: prime-rc/weatherbus-*-SNAPSHOT.jar
- name: web
  plan:
    - get: web
      trigger: true
    - task: build
      file: web/concourse/build.yml
